[package]
name = "test-occ-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
cxx = "1"

[build-dependencies]
cxx-build = "1"
home = "0.5.4"
